stages:
  train-synth:
    cmd: brainways-reg-model train --config reg --train-data data/synth.zip --output trained_model/synth
    deps:
      - data/synth.zip
      - data/real.zip
      - src/brainways_reg_model/model/dataset.py
      - src/brainways_reg_model/model/model.py
      - src/brainways_reg_model/model/train.py
    params:
      - default
      - reg
    outs:
      - trained_model/synth/logs
      - trained_model/synth/model.ckpt
  eval:
    cmd: brainways-reg-model evaluate --checkpoint trained_model/synth/model.ckpt --output trained_model/synth/scores.json
    deps:
      - trained_model/synth/model.ckpt
      - src/brainways_reg_model/model/evaluate.py
    metrics:
      - trained_model/synth/scores.json:
          cache: false
  train-real:
    cmd: brainways-reg-model train --config finetune --train-data data/real.zip --output trained_model/real --pretrained-checkpoint trained_model/synth/model.ckpt
    deps:
      - trained_model/synth/model.ckpt
      - data/real.zip
      - src/brainways_reg_model/model/dataset.py
      - src/brainways_reg_model/model/model.py
      - src/brainways_reg_model/model/train.py
    params:
      - default
      - reg
      - finetune
    outs:
      - trained_model/real/logs
      - trained_model/real/model.ckpt
  eval-finetune:
    cmd: brainways-reg-model evaluate
    deps:
      - trained_model/real/model.ckpt
      - src/brainways_reg_model/model/evaluate.py
    metrics:
      - trained_model/real/scores.json:
          cache: false
