stages:
  train:
    cmd: python -m brainways_reg_model.model.train
    deps:
      - data/synth.zip
      - data/real.zip
      - src/brainways_reg_model/model/dataset.py
      - src/brainways_reg_model/model/model.py
      - src/brainways_reg_model/model/train.py
    params:
      - default
      - reg
    outs:
      - trained_model/synth/logs
      - trained_model/synth/model.ckpt
  eval:
    cmd: python -m brainways_reg_model.model.evaluate trained_model/synth/model.ckpt trained_model/synth/scores.json
    deps:
      - trained_model/synth/model.ckpt
      - src/brainways_reg_model/model/evaluate.py
    metrics:
      - trained_model/synth/scores.json:
          cache: false
  finetune:
    cmd: python -m brainways_reg_model.model.finetune
    deps:
      - trained_model/synth/model.ckpt
      - data/real.zip
      - src/brainways_reg_model/model/dataset.py
      - src/brainways_reg_model/model/model.py
      - src/brainways_reg_model/model/finetune.py
    params:
      - default
      - reg
      - finetune
    outs:
      - trained_model/real/logs
      - trained_model/real/model.ckpt
  eval-finetune:
    cmd: python -m brainways_reg_model.model.evaluate trained_model/real/model.ckpt trained_model/real/scores.json
    deps:
      - trained_model/real/model.ckpt
      - src/brainways_reg_model/model/evaluate.py
    metrics:
      - trained_model/real/scores.json:
          cache: false
