# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.1.dev1+g7f1e321.d20220717"
__version_tuple__ = version_tuple = (0, 1, "dev1", "g7f1e321.d20220717")
